meta:
  author: dbd
units:
  kx: cx
  ky: cy
  px: kx + 4
  py: ky + 4
points:
  key:
    footprints:
      choc_hotswap:
        type: choc
        params:
          hotswap: true
          reverse: true
          keycaps: true
        nets:
          from: =colrow
          to: =column_net
      diode:
        type: diode
        nets:
          from: =colrow
          to: =row_net
        anchor:
          shift: [0, -5]
  zones:
    matrix:
      anchor:
          shift: [100, -100]
      key.padding: ky
      columns:
        outer:
          key:
            spread: kx
            column_net: P21
        pinky:
          key:
            spread: kx
            column_net: P20
        ring:
          key:
            stagger: 5
            bind: [0, 10, 12, 10]
            spread: kx
            column_net: P19
        middle:
          key:
            stagger: 6
            bind: [0, 10, 12, 10]
            spread: kx
            column_net: P18
        index:
          key:
            stagger: -6
            bind: [0, 10, 12, 10]
            spread: kx
            column_net: P15
        inner:
          key:
            stagger: -5
            bind: [0, 10, 12, 10]
            spread: kx
            column_net: P14
      rows:
        mods:
          row_net: P7
        lower:
          row_net: P8
        home:
          row_net: P9
        upper:
          row_net: P10
        number:
          row_net: P16
    thumb:
      anchor:
        ref: matrix_ring_mods
      columns:
        end:
          key: 
             shift: [0, -30]
             spread: kx
             column_net: P20
        mute:
          key: 
             shift: [0, -30]
             spread: kx
             column_net: P19
        alt:
          key: 
             shift: [0, -30]
             spread: kx
             column_net: P18
        space:
          key:
            rotate: -10
            shift: [3, -33]
            bind: [5, 0, 0, 0]
            spread: kx
            column_net: P15
        layer:
          key:
            rotate: -20
            shift: [5, -40]
            bind: [5, 0, 5, 30]
            spread: kx
            column_net: P14
      rows:
        cluster:
          row_net: P6
          key: 
             shift: [0, -10]
outlines:
  holes:
    - where: true
      what: rectangle
      size: 18
  edge:
    - where: true
      what: rectangle
      size: 18
      bound: true
  board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_outer_number
          shift: [-0.5px,0.5py]
        - ref: matrix_ring_number
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_number
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_number
          shift: [0.5px,0.5py]
        - ref: matrix_inner_number
          shift: [0.5px,0.5py]
        - ref: matrix_inner_number
          shift: [1.5px,0.5py]
        - ref: matrix_inner_mods
          shift: [1.5px,0.5py]
        - ref: thumb_layer_cluster
          shift: [0.5px,0.5py]
        - ref: thumb_layer_cluster
          shift: [0.5px,-0.5py]
        - ref: thumb_layer_cluster
          shift: [-0.5px,-0.5py]
        - ref: thumb_space_cluster
          shift: [-0.5px,-0.5py]
        - ref: thumb_alt_cluster
          shift: [-0.5px,-0.5py]
        - ref: thumb_end_cluster
          shift: [-0.5px,-0.5py]
        - ref: matrix_pinky_mods
          shift: [-0.5px,-0.5py]
        - ref: matrix_outer_mods
          shift: [-0.5px,-0.5py]
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [kx-0.5,ky-0.5]
  plate:
    - board
    - -keys
cases:
  test:
  - what: outline
    name: edge
    extrude: 5
pcbs.test:
  outlines:
    - outline: board
  footprints:
    choc_hotswap:
        what: choc
        where: true
        params:
          from: '{{colrow}}'
          to: '{{column_net}}'
          keycaps: true
          reverse: true
          hotswap: true
    diode:
      what: diode
      where:
        - /matrix_.*/
        - /thumb_.*/
      adjust.shift: [0, -5]
      params:
        from: "{{colrow}}"
        to: "{{row_net}}"
    promicro:
      what: promicro
      where:
        ref: matrix_inner_number
        shift: [1px,-0.45py]
        rotate: -90
